package model;

import java.util.Arrays;


public class AlgorithmCYK {

	private String[][] gram;
	private String w;


	public AlgorithmCYK(String[][] g,String chain) {
		gram = g;
		w = chain;
	}
	
	/*
	* 
	* This is the main method that runs the CYK algorithm
	* pre: gram!=null,w!=null
	* post: Validates if the grammar generates the language string
	@param 
	@return Returns a boolean type value where it is affirmative if the grammar generates the string w, otherwise it is false
	*/
	public boolean generateCYKMatrix() throws ArrayIndexOutOfBoundsException{
		boolean generate=false;
		
		String[][] resultMatrix = new String[w.length()+1][w.length()+1];
		
		for (String[] row: resultMatrix) {
		    Arrays.fill(row, "");
		}
		
		System.out.println("w: "+w);

		for(int wL=0;wL<w.length();wL++) {
			String result="";
			String letter = ""+w.charAt(wL);
			for(int i=0;i<gram.length;i++) {
				for(int j=1;j<gram[i].length;j++) {
					if(letter.equals(gram[i][j])) {
						result+=gram[i][0];
					}
				}
			}
			resultMatrix[wL][wL]=result;
		}
		
		for(int i=1;i<w.length();i++) {
			for(int j=i;j<=w.length();j++) {
				String pw="";
				for(int k=j-i;k<j;k++) {
					pw += combineStrings(resultMatrix[j-i][k], resultMatrix[k+1][j]);
				}
				resultMatrix[j-i][j] = pw;
			}
		}

		if(resultMatrix[0][w.length() - 1].indexOf("S") >= 0) {
			generate=true;
		}
		
		for (int i = 0; i < resultMatrix.length; i++) {
			for (int j = 0; j < resultMatrix[i].length; j++) {
				System.out.print(resultMatrix[i][j] + " ");
			}
			System.out.println();
		}
		
		return generate;
	}
	/*
	* 
	* This method validates if the input string is contained in the grammar
	* pre: gram!=null
	* post: Verify if the input string is contain on the grammar 
	@param search is a chain that we want to search on the grammar
	@return A string of all the sub-partitions of the grammar that the input string contains 
	*/
	public String verifyIfExist(String search) {
		String result="";
		int j=0;
		 for(int i = 0; i < gram.length; i++) {
	        	
	            for( j = 0; j < gram[i].length ; j++){
	            	
	                if(gram[i][j].equals(search)){
	                	
	                    result += gram[i][0];
	                    
	                }
	            }
	            
	        }
		 return result;
	}
	/*
	* 
	* this method combines two input strings
	* pre: gram!=null
	* post: a string with the letters generated by the grammar given the two strings
	@param chain1,chain2 are the string we want to know if they are part of the grammar 
	@return the string validated in the grammar
	*/
	public String combineStrings(String chain1,String chain2) {
		
		String result= "";
		String str = "";
		if(chain1!=null && chain2!=null) {
			for(int i = 0; i < chain1.length(); i++){

				for(int j = 0; j < chain2.length(); j++){
					str="";
					str +=  chain1.charAt(i)+""+chain2.charAt(j);
					result+=verifyIfExist(str);
						
					
				}
			}
		}

		return result;	
	}

}
